- name: Set machine-specific variables
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - ansible.builtin.set_fact:
        git_user_name: "Your Name"
        git_user_email: "you@example.com"
        tailscale_tag: "workstation"  # role prepends "tag:" automatically; or "server" etc.
        tailscale_config_file: "machinename-tailscale.yml"  # copy from example-tailscale.yml
        dns_hostname: "machinename"
        dns_services:
          - traefik
          - dozzle
        data_disk_mountpoint: /docker-data

- import_playbook: ../bootstrap.yml
- import_playbook: ../apps.yml
- import_playbook: ../develop.yml
- import_playbook: ../tailscale.yml
- import_playbook: ../docker.yml
- import_playbook: ../dns.yml
- import_playbook: ../setup-storage.yml
