---
cluster_name: swintronics
server_domain: "swintronics.com"
cert_resolver: "production"
docker_services_path: "/home/{{ admin_user }}/{{ cluster_name }}/docker-services"
immich_data_location: "{{ data_disk_mountpoint }}/volumes/immich"
