#cloud-config
# This example assumes a default Ubuntu cloud image, which should contain
# the required software to be managed remotely by Ansible.

package_update: true
package_upgrade: true

#Do not accept SSH password authention
ssh_pwauth: false

timezone: ${timezone}
packages:
  - apt-config-auto-update  # https://linuxcapable.com/how-to-configure-unattended-upgrades-on-ubuntu-linux/
  - apt-transport-https
  - ca-certificates
  - curl
  - git
  - gnupg
  - gnupg-agent
  - jq
  - software-properties-common
  - unattended-upgrades

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/99-enable-ipv4-forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

# create the docker group
groups:
  - docker

users:
  - name: "${admin_user}"
    sudo: ALL=(ALL) NOPASSWD:ALL
    gcos: "Admin User"
    groups: [sudo, adm, docker]
    shell: /bin/bash
    ssh-authorized-keys:
    - "${admin_public_key}"

# Install Docker, for production, consider pinning to stable versions
runcmd:
  - echo "Installing docker"
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  - echo "Configuring unattended upgrades"
  - dpkg-reconfigure unattended-upgrades

