#cloud-config

ssh_pwauth: false

timezone: ${timezone}

# Enable ipv4 forwarding
write_files:
  - path: /etc/sysctl.d/99-enable-ipv4-forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

# create the docker group so the admin user can be added before Docker is installed
groups:
  - docker

users:
  - name: "${admin_user}"
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    groups: [sudo, adm, docker]
    shell: /bin/bash
    ssh_authorized_keys:
    - "${admin_public_key}"

runcmd:
  - [sysctl, -p, /etc/sysctl.d/99-enable-ipv4-forwarding.conf]
  - [mkdir, -p, "${mountpoint}"]
