---
server_admin_username: neil
tz: "America/New_York"
server_domain: "swintronics.com"
cert_resolver: "production"
dns_hostname: "swintronics"
tailscale_tag: "server"
tailscale_authkey_secret: "TS_XPS13_AUTH_KEY"
tailscale_subnet: "192.168.1.0/24"
tailscale_exit_node: true
use_btrfs: true
data_disk_mountpoint: /docker-data
