include:
  - "../docker-network-common.yml"

services:
  traefik:
    image: traefik:v3.4.1
    container_name: traefik
    restart: always
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443      
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/configs:/configs:ro
      - ./data/acme.json:/acme.json:rw
      - ./data/logs:/logs:rw
    environment:
      - TZ=America/New_York
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    read_only: true
    security_opt:
      - no-new-privileges:true
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-https.entrypoints=https
      - traefik.http.routers.traefik-https.rule=Host(`myproxy.swintronics.com`)
      - traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIKADMIN}
      # - traefik.http.routers.traefik-https.middlewares=traefik-auth
      - traefik.http.routers.traefik-https.service=api@internal
      - traefik.http.routers.traefik-https.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-https.tls.domains[0].main=swintronics.com
      - traefik.http.routers.traefik-https.tls.domains[0].sans=*.swintronics.com

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    networks:
      - proxy
    restart: unless-stopped
    labels:
     - traefik.enable=true
     - traefik.http.routers.whoami-https.rule=Host(`whoami.swintronics.com`)
     - traefik.http.routers.whoami-https.entrypoints=https
     - traefik.http.routers.whoami-https.service=whoami
     - traefik.http.services.whoami.loadbalancer.server.scheme=https
     - traefik.http.services.whoami.loadbalancer.server.port=8443
