services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - "8081:8080"  # Expose cAdvisor web UI on port 8081
    volumes:
      - "/:/rootfs:ro"              # Mount the host filesystem
      - "/var/run:/var/run:ro"      # Mount the Docker socket for container monitoring
      - "/sys:/sys:ro"              # Mount /sys for system stats
      - "/var/lib/docker/:/var/lib/docker:ro"  # Mount Docker data directory
    privileged: true                # This grants cAdvisor more permissions for system stats
    labels:
      traefik.enable: true
      traefik.http.routers.cadvisor.entrypoints: websecure
      traefik.http.routers.cadvisor.rule: Host(`cadvisor.${SERVER_DOMAIN}`)
      traefik.http.routers.cadvisor.tls.certresolver: ${CERT_RESOLVER}