
services:
  httpbin:
    image: "kennethreitz/httpbin"
    container_name: "httpbin"
    restart: "no"
    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.httpbin.rule=Host(`httpbin.swintronics.com`)"
      - "traefik.http.routers.httpbin.entrypoints=websecure"
      - "traefik.http.routers.httpbin.tls.certresolver=letsencrypt"
    profiles:
      - debug